/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutIroncladCommercialFloorsVancouverBcRouteImport } from './routes/about-ironclad-commercial-floors-vancouver-bc'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CommercialEpoxyFlooringVancouverBcRouteImport } from './routes/commercial-epoxy-flooring-vancouver-bc'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactIroncladCommercialFloorsVancouverBcRouteImport } from './routes/contact-ironclad-commercial-floors-vancouver-bc'
import { Route as FlooringInstallationVancouverBcRouteImport } from './routes/flooring-installation-vancouver-bc'
import { Route as FlooringRepairVancouverBcRouteImport } from './routes/flooring-repair-vancouver-bc'
import { Route as FlooringReplacementVancouverBcRouteImport } from './routes/flooring-replacement-vancouver-bc'
import { Route as GarageEpoxyFlooringVancouverBcRouteImport } from './routes/garage-epoxy-flooring-vancouver-bc'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocationSlugRouteImport } from './routes/location/$slug'
import { Route as ServiceSlugRouteImport } from './routes/service/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIroncladCommercialFloorsVancouverBcRoute =
  AboutIroncladCommercialFloorsVancouverBcRouteImport.update({
    id: '/about-ironclad-commercial-floors-vancouver-bc',
    path: '/about-ironclad-commercial-floors-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialEpoxyFlooringVancouverBcRoute =
  CommercialEpoxyFlooringVancouverBcRouteImport.update({
    id: '/commercial-epoxy-flooring-vancouver-bc',
    path: '/commercial-epoxy-flooring-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIroncladCommercialFloorsVancouverBcRoute =
  ContactIroncladCommercialFloorsVancouverBcRouteImport.update({
    id: '/contact-ironclad-commercial-floors-vancouver-bc',
    path: '/contact-ironclad-commercial-floors-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlooringInstallationVancouverBcRoute =
  FlooringInstallationVancouverBcRouteImport.update({
    id: '/flooring-installation-vancouver-bc',
    path: '/flooring-installation-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlooringRepairVancouverBcRoute =
  FlooringRepairVancouverBcRouteImport.update({
    id: '/flooring-repair-vancouver-bc',
    path: '/flooring-repair-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlooringReplacementVancouverBcRoute =
  FlooringReplacementVancouverBcRouteImport.update({
    id: '/flooring-replacement-vancouver-bc',
    path: '/flooring-replacement-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const GarageEpoxyFlooringVancouverBcRoute =
  GarageEpoxyFlooringVancouverBcRouteImport.update({
    id: '/garage-epoxy-flooring-vancouver-bc',
    path: '/garage-epoxy-flooring-vancouver-bc',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ironclad-commercial-floors-vancouver-bc': typeof AboutIroncladCommercialFloorsVancouverBcRoute
  '/blogs': typeof BlogsRoute
  '/commercial-epoxy-flooring-vancouver-bc': typeof CommercialEpoxyFlooringVancouverBcRoute
  '/contact': typeof ContactRoute
  '/contact-ironclad-commercial-floors-vancouver-bc': typeof ContactIroncladCommercialFloorsVancouverBcRoute
  '/flooring-installation-vancouver-bc': typeof FlooringInstallationVancouverBcRoute
  '/flooring-repair-vancouver-bc': typeof FlooringRepairVancouverBcRoute
  '/flooring-replacement-vancouver-bc': typeof FlooringReplacementVancouverBcRoute
  '/garage-epoxy-flooring-vancouver-bc': typeof GarageEpoxyFlooringVancouverBcRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ironclad-commercial-floors-vancouver-bc': typeof AboutIroncladCommercialFloorsVancouverBcRoute
  '/blogs': typeof BlogsRoute
  '/commercial-epoxy-flooring-vancouver-bc': typeof CommercialEpoxyFlooringVancouverBcRoute
  '/contact': typeof ContactRoute
  '/contact-ironclad-commercial-floors-vancouver-bc': typeof ContactIroncladCommercialFloorsVancouverBcRoute
  '/flooring-installation-vancouver-bc': typeof FlooringInstallationVancouverBcRoute
  '/flooring-repair-vancouver-bc': typeof FlooringRepairVancouverBcRoute
  '/flooring-replacement-vancouver-bc': typeof FlooringReplacementVancouverBcRoute
  '/garage-epoxy-flooring-vancouver-bc': typeof GarageEpoxyFlooringVancouverBcRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ironclad-commercial-floors-vancouver-bc': typeof AboutIroncladCommercialFloorsVancouverBcRoute
  '/blogs': typeof BlogsRoute
  '/commercial-epoxy-flooring-vancouver-bc': typeof CommercialEpoxyFlooringVancouverBcRoute
  '/contact': typeof ContactRoute
  '/contact-ironclad-commercial-floors-vancouver-bc': typeof ContactIroncladCommercialFloorsVancouverBcRoute
  '/flooring-installation-vancouver-bc': typeof FlooringInstallationVancouverBcRoute
  '/flooring-repair-vancouver-bc': typeof FlooringRepairVancouverBcRoute
  '/flooring-replacement-vancouver-bc': typeof FlooringReplacementVancouverBcRoute
  '/garage-epoxy-flooring-vancouver-bc': typeof GarageEpoxyFlooringVancouverBcRoute
  '/locations': typeof LocationsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/location/$slug': typeof LocationSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-ironclad-commercial-floors-vancouver-bc'
    | '/blogs'
    | '/commercial-epoxy-flooring-vancouver-bc'
    | '/contact'
    | '/contact-ironclad-commercial-floors-vancouver-bc'
    | '/flooring-installation-vancouver-bc'
    | '/flooring-repair-vancouver-bc'
    | '/flooring-replacement-vancouver-bc'
    | '/garage-epoxy-flooring-vancouver-bc'
    | '/locations'
    | '/projects'
    | '/services'
    | '/blog/$slug'
    | '/location/$slug'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-ironclad-commercial-floors-vancouver-bc'
    | '/blogs'
    | '/commercial-epoxy-flooring-vancouver-bc'
    | '/contact'
    | '/contact-ironclad-commercial-floors-vancouver-bc'
    | '/flooring-installation-vancouver-bc'
    | '/flooring-repair-vancouver-bc'
    | '/flooring-replacement-vancouver-bc'
    | '/garage-epoxy-flooring-vancouver-bc'
    | '/locations'
    | '/projects'
    | '/services'
    | '/blog/$slug'
    | '/location/$slug'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-ironclad-commercial-floors-vancouver-bc'
    | '/blogs'
    | '/commercial-epoxy-flooring-vancouver-bc'
    | '/contact'
    | '/contact-ironclad-commercial-floors-vancouver-bc'
    | '/flooring-installation-vancouver-bc'
    | '/flooring-repair-vancouver-bc'
    | '/flooring-replacement-vancouver-bc'
    | '/garage-epoxy-flooring-vancouver-bc'
    | '/locations'
    | '/projects'
    | '/services'
    | '/blog/$slug'
    | '/location/$slug'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutIroncladCommercialFloorsVancouverBcRoute: typeof AboutIroncladCommercialFloorsVancouverBcRoute
  BlogsRoute: typeof BlogsRoute
  CommercialEpoxyFlooringVancouverBcRoute: typeof CommercialEpoxyFlooringVancouverBcRoute
  ContactRoute: typeof ContactRoute
  ContactIroncladCommercialFloorsVancouverBcRoute: typeof ContactIroncladCommercialFloorsVancouverBcRoute
  FlooringInstallationVancouverBcRoute: typeof FlooringInstallationVancouverBcRoute
  FlooringRepairVancouverBcRoute: typeof FlooringRepairVancouverBcRoute
  FlooringReplacementVancouverBcRoute: typeof FlooringReplacementVancouverBcRoute
  GarageEpoxyFlooringVancouverBcRoute: typeof GarageEpoxyFlooringVancouverBcRoute
  LocationsRoute: typeof LocationsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationSlugRoute: typeof LocationSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-ironclad-commercial-floors-vancouver-bc': {
      id: '/about-ironclad-commercial-floors-vancouver-bc'
      path: '/about-ironclad-commercial-floors-vancouver-bc'
      fullPath: '/about-ironclad-commercial-floors-vancouver-bc'
      preLoaderRoute: typeof AboutIroncladCommercialFloorsVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-epoxy-flooring-vancouver-bc': {
      id: '/commercial-epoxy-flooring-vancouver-bc'
      path: '/commercial-epoxy-flooring-vancouver-bc'
      fullPath: '/commercial-epoxy-flooring-vancouver-bc'
      preLoaderRoute: typeof CommercialEpoxyFlooringVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-ironclad-commercial-floors-vancouver-bc': {
      id: '/contact-ironclad-commercial-floors-vancouver-bc'
      path: '/contact-ironclad-commercial-floors-vancouver-bc'
      fullPath: '/contact-ironclad-commercial-floors-vancouver-bc'
      preLoaderRoute: typeof ContactIroncladCommercialFloorsVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flooring-installation-vancouver-bc': {
      id: '/flooring-installation-vancouver-bc'
      path: '/flooring-installation-vancouver-bc'
      fullPath: '/flooring-installation-vancouver-bc'
      preLoaderRoute: typeof FlooringInstallationVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flooring-repair-vancouver-bc': {
      id: '/flooring-repair-vancouver-bc'
      path: '/flooring-repair-vancouver-bc'
      fullPath: '/flooring-repair-vancouver-bc'
      preLoaderRoute: typeof FlooringRepairVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flooring-replacement-vancouver-bc': {
      id: '/flooring-replacement-vancouver-bc'
      path: '/flooring-replacement-vancouver-bc'
      fullPath: '/flooring-replacement-vancouver-bc'
      preLoaderRoute: typeof FlooringReplacementVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage-epoxy-flooring-vancouver-bc': {
      id: '/garage-epoxy-flooring-vancouver-bc'
      path: '/garage-epoxy-flooring-vancouver-bc'
      fullPath: '/garage-epoxy-flooring-vancouver-bc'
      preLoaderRoute: typeof GarageEpoxyFlooringVancouverBcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutIroncladCommercialFloorsVancouverBcRoute:
    AboutIroncladCommercialFloorsVancouverBcRoute,
  BlogsRoute: BlogsRoute,
  CommercialEpoxyFlooringVancouverBcRoute:
    CommercialEpoxyFlooringVancouverBcRoute,
  ContactRoute: ContactRoute,
  ContactIroncladCommercialFloorsVancouverBcRoute:
    ContactIroncladCommercialFloorsVancouverBcRoute,
  FlooringInstallationVancouverBcRoute: FlooringInstallationVancouverBcRoute,
  FlooringRepairVancouverBcRoute: FlooringRepairVancouverBcRoute,
  FlooringReplacementVancouverBcRoute: FlooringReplacementVancouverBcRoute,
  GarageEpoxyFlooringVancouverBcRoute: GarageEpoxyFlooringVancouverBcRoute,
  LocationsRoute: LocationsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationSlugRoute: LocationSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
